# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dhawal Joharapurkar
email: dmjan21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Dhawal Joharapurkar's academic website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dhawaljoh.github.com" # the base hostname & protocol for your site
future: true # allows future dated posts

#social networks
twitter_username: dhawaljoh
github_username: dhawaljoh
facebook_username: dhawaljoh
linkedin_username: dhawaljoh
disqus_username: dhawaljoh

# Build settings
markdown: kramdown

# Other Options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"